#!/bin/bash

if pgrep cava; then
    pkill cava
    exec eww open --toggle visualizer &
    # echo "Off" > $HOME/.config/eww/Player/status/vz-status
    eww close lyrics
    exit 1
else
    exec cava &
    exec eww open --toggle visualizer &
    # echo "On" > $HOME/.config/eww/Player/status/vz-status
    eww close lyrics
fi
exit
